//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Player/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Controls"",
            ""id"": ""2736694b-7247-4da4-8f50-f013159fb588"",
            ""actions"": [
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2d57bc23-4625-4c6d-aa6e-78e9765d3965"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""33c66f2d-a8da-4eb2-99ee-28d36d1b429c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""56a8b0c4-b128-40a8-a8ae-d08921222a2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractA"",
                    ""type"": ""Button"",
                    ""id"": ""a4582071-4e9d-41cd-b56d-e6eb30c588bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelB"",
                    ""type"": ""Button"",
                    ""id"": ""4e4ae327-318a-496e-ae8a-339014c587dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuStart"",
                    ""type"": ""Button"",
                    ""id"": ""2e4a5685-e615-40dc-89c0-37c9231288aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerupScrollLeft"",
                    ""type"": ""Button"",
                    ""id"": ""09511f99-ff18-4131-861c-857ea9da1e56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerupScrollRight"",
                    ""type"": ""Button"",
                    ""id"": ""6bddf715-7dde-47b8-bb31-f6b339a23ad8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UsePowerup"",
                    ""type"": ""Button"",
                    ""id"": ""d49b9abe-1689-45d1-8fb9-cc71fe2a7f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f1652067-489d-48cd-be5b-44ca27c765de"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d1e0b34-76da-4d34-a92a-14e594e65013"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dad8aeeb-974d-4af2-ac95-55f49c331bd0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""deeb7d17-44a7-4fc0-826f-215d3aaf0a54"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""581e98e9-5d53-4605-9e8a-1d862b84465f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a82b1f1b-0993-414c-9d42-f780e7c197d9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8030ce8a-468d-4b50-b9ac-9f776a1bd07a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eb7a86ed-aed0-4301-9633-ffa053789f5c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""26bf286d-8363-4bf6-a3b2-e8b5e4e7f621"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2881a75b-0177-4164-870e-dd14e2820a24"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13466dea-6e5c-4a86-89db-6912fdc54dea"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1ba8b65-19ba-45f5-8038-f2687aad154e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""187e16c5-f150-47b1-9dad-be06b608e4e9"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43be329a-6ff8-4bd6-8331-52ddb8718f94"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""056184cb-0872-4f3f-b5e7-be0c705bda6b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""639fc0dc-5a1e-4dc9-8580-da53e9c3e03e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00289a4a-e99e-47e4-ba7b-776e068fb858"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c84f978e-00a0-47fc-b83e-2b81df44e591"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5c8650-f463-4eb8-9c51-063ea6d95970"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44489231-d581-4355-bae5-024795f6d53e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4b394f4-419b-480c-86b0-f4276cb41743"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96c672c0-4c97-4eeb-ba42-c6fc5bc53191"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d9705e2-6cc0-4fc0-aace-928b270f870d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7136110-0145-4243-ab12-4bc72a76d280"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d793472c-7334-4f29-99a8-beb82e1d3c10"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed81d443-005a-49ce-a931-f75de9059256"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControlsV2"",
            ""id"": ""2f55c3d6-4f77-4023-bf79-99150d7b34e3"",
            ""actions"": [
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c24db4c9-444d-4c39-935a-d5cccb8018e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7c8df745-3068-4ae5-83d5-ef2a906d89db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""8d37c2ff-7ed1-4d2a-b535-de376eee19f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractA"",
                    ""type"": ""Button"",
                    ""id"": ""f15e1857-03f6-436d-82db-c97ae2cf142e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelB"",
                    ""type"": ""Button"",
                    ""id"": ""9098e0cf-aad2-4acf-b3ff-3237c4cf8bbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuStart"",
                    ""type"": ""Button"",
                    ""id"": ""2a0d727a-c94e-43dc-bcf6-44db80ab64ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerupScrollLeft"",
                    ""type"": ""Button"",
                    ""id"": ""59d7f044-f7ce-4826-bb93-b93c4e524e80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerupScrollRight"",
                    ""type"": ""Button"",
                    ""id"": ""b34f6320-20df-4ebc-b112-fd303c3c3278"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UsePowerup"",
                    ""type"": ""Button"",
                    ""id"": ""d371a2eb-b773-4d6a-9399-0969f5e2a4f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpSpace"",
                    ""type"": ""Button"",
                    ""id"": ""634b790c-c681-4cdc-b1e7-c38e07f565d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8b6c55bd-ea04-4dc4-bfc5-4505c63dd7c5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86891c2b-00e5-4cec-a263-51a5e4eff5dc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ad6fc8f-7caa-4762-b87d-1d2b421da625"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""57dcff84-ad65-41b5-a299-fd25add9a07d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b2891a6c-55c5-4c2f-912d-770953cf0c2d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""303fed67-1f5a-40a4-8300-a195065a9857"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""97cbf25a-9c9d-4a9c-95cb-e1fac375f1c5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46a5d627-9ba8-4c0c-a718-f48fdc4fb82f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""42fa82bf-6251-4678-b46a-8b91ab97f700"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97c2dd8a-f352-4565-905f-6ceb7046cc12"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""faf1918a-c62f-4e31-9faa-69e1841669c0"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53687832-7a94-4e43-9e3b-980a6fad40ea"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4b237f7-2f28-49ae-a5b2-7a6b51316078"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35463675-6bfd-45c5-aadf-9d3d51018480"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16a4d02a-18e1-444a-b7ee-5d44a71c57ff"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1757558-5e73-4730-862e-5295ab127587"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b7b0d7a-8b8a-4ad0-b97b-cd3ebbc8ec51"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc39c623-78ec-47c3-871b-1bacb8ef5f6e"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf0bdf6-7a40-4cd1-a015-36dc8435c70e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b657934d-bf1c-41dc-b10b-7f2fb0aa9805"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b007eb5-40e2-4240-b0c4-4d029d253c30"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""221ac0e0-502f-41e8-bb68-c78ac7ba7cfe"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37b24a5a-4ae2-4ed0-86e8-b0d7ced84856"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""121b3cf1-26b8-4ac3-a101-e4b500304cd5"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b703c16c-fd83-4e17-9518-dcd2d5a4cf5f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8a4bef-45bf-4c9f-8c18-09a960d049c8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsePowerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cd5d27e-f699-4c54-8a2e-0856bf8664d9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dc0c2b0-5da0-4d7c-9a86-c99afab9f693"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0a2eeab-a243-409f-abba-daeed0d4eb89"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7770a6fa-11d1-4da5-b45e-ae81f2f47eaf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f3e9f47-a69e-489d-baa0-755817b1a19c"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerupScrollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""7c9fa403-f124-4f9a-9d3b-346da08c524f"",
            ""actions"": [
                {
                    ""name"": ""NavigateMenu"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e1b812c9-81f0-46c3-af9b-caa83fd13bf6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select/Submit"",
                    ""type"": ""Button"",
                    ""id"": ""194308ba-4e10-4b2e-83df-7d8a5bcc127d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""72379b9b-89c8-41b1-a013-c604dff16b61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause/Unpause"",
                    ""type"": ""Button"",
                    ""id"": ""a88c9e0b-4a8f-4b08-b844-1424688631b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""D-Pad [GamePad]"",
                    ""id"": ""4c56a0a9-f6b9-41bc-bee2-89881064168f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0bce64a3-6146-4824-ab11-69ce05a1d81f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3cdc8e35-36d5-4f8c-a5d0-26a3e2689875"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cdd9ba3b-be5f-4797-baf0-704dbccef0c6"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""69c822bf-cfb6-46ad-857b-200bfd8b5b9a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick [GamePad]"",
                    ""id"": ""2ae4d0e1-9444-474e-b7a6-09627d6810db"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""256a8bbe-905f-45fd-9fc8-386309e0ab7d"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dbad552e-fdc3-4c18-be24-83a21304147c"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""54b83abf-0dff-42d3-ba16-5714b29077e5"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ef4ef937-80e8-4b93-9d92-47d3c098839a"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6ef8f9db-f90a-4ca7-b5ad-71a30b9e75f2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""58db846d-d9c4-4466-a08d-b892e0830d53"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0bef4c3f-f6d5-43f3-ade8-1362846a7a0b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bf20650e-346e-4bd9-897e-8a04a4a54a0f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0fbe74dc-e68d-45a2-9611-d562086f7b1a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1cf41864-007b-4f6b-8d10-c1659b0b5357"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select/Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""024a274d-5466-49c8-9578-019431219ca8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select/Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f1cefdb-819a-4b98-9bd0-b74055300000"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75be1dbb-d6f9-4a5d-9994-9118462ea060"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""068e3ce2-e084-49b4-b472-80c03e72f911"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause/Unpause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea40b4e4-d91b-4106-ac02-5465123d12a4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause/Unpause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controls
        m_Controls = asset.FindActionMap("Controls", throwIfNotFound: true);
        m_Controls_Camera = m_Controls.FindAction("Camera", throwIfNotFound: true);
        m_Controls_Movement = m_Controls.FindAction("Movement", throwIfNotFound: true);
        m_Controls_Sprint = m_Controls.FindAction("Sprint", throwIfNotFound: true);
        m_Controls_InteractA = m_Controls.FindAction("InteractA", throwIfNotFound: true);
        m_Controls_CancelB = m_Controls.FindAction("CancelB", throwIfNotFound: true);
        m_Controls_MenuStart = m_Controls.FindAction("MenuStart", throwIfNotFound: true);
        m_Controls_PowerupScrollLeft = m_Controls.FindAction("PowerupScrollLeft", throwIfNotFound: true);
        m_Controls_PowerupScrollRight = m_Controls.FindAction("PowerupScrollRight", throwIfNotFound: true);
        m_Controls_UsePowerup = m_Controls.FindAction("UsePowerup", throwIfNotFound: true);
        // ControlsV2
        m_ControlsV2 = asset.FindActionMap("ControlsV2", throwIfNotFound: true);
        m_ControlsV2_Camera = m_ControlsV2.FindAction("Camera", throwIfNotFound: true);
        m_ControlsV2_Movement = m_ControlsV2.FindAction("Movement", throwIfNotFound: true);
        m_ControlsV2_Sprint = m_ControlsV2.FindAction("Sprint", throwIfNotFound: true);
        m_ControlsV2_InteractA = m_ControlsV2.FindAction("InteractA", throwIfNotFound: true);
        m_ControlsV2_CancelB = m_ControlsV2.FindAction("CancelB", throwIfNotFound: true);
        m_ControlsV2_MenuStart = m_ControlsV2.FindAction("MenuStart", throwIfNotFound: true);
        m_ControlsV2_PowerupScrollLeft = m_ControlsV2.FindAction("PowerupScrollLeft", throwIfNotFound: true);
        m_ControlsV2_PowerupScrollRight = m_ControlsV2.FindAction("PowerupScrollRight", throwIfNotFound: true);
        m_ControlsV2_UsePowerup = m_ControlsV2.FindAction("UsePowerup", throwIfNotFound: true);
        m_ControlsV2_JumpSpace = m_ControlsV2.FindAction("JumpSpace", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_NavigateMenu = m_UI.FindAction("NavigateMenu", throwIfNotFound: true);
        m_UI_SelectSubmit = m_UI.FindAction("Select/Submit", throwIfNotFound: true);
        m_UI_Back = m_UI.FindAction("Back", throwIfNotFound: true);
        m_UI_PauseUnpause = m_UI.FindAction("Pause/Unpause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controls
    private readonly InputActionMap m_Controls;
    private List<IControlsActions> m_ControlsActionsCallbackInterfaces = new List<IControlsActions>();
    private readonly InputAction m_Controls_Camera;
    private readonly InputAction m_Controls_Movement;
    private readonly InputAction m_Controls_Sprint;
    private readonly InputAction m_Controls_InteractA;
    private readonly InputAction m_Controls_CancelB;
    private readonly InputAction m_Controls_MenuStart;
    private readonly InputAction m_Controls_PowerupScrollLeft;
    private readonly InputAction m_Controls_PowerupScrollRight;
    private readonly InputAction m_Controls_UsePowerup;
    public struct ControlsActions
    {
        private @PlayerControls m_Wrapper;
        public ControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Camera => m_Wrapper.m_Controls_Camera;
        public InputAction @Movement => m_Wrapper.m_Controls_Movement;
        public InputAction @Sprint => m_Wrapper.m_Controls_Sprint;
        public InputAction @InteractA => m_Wrapper.m_Controls_InteractA;
        public InputAction @CancelB => m_Wrapper.m_Controls_CancelB;
        public InputAction @MenuStart => m_Wrapper.m_Controls_MenuStart;
        public InputAction @PowerupScrollLeft => m_Wrapper.m_Controls_PowerupScrollLeft;
        public InputAction @PowerupScrollRight => m_Wrapper.m_Controls_PowerupScrollRight;
        public InputAction @UsePowerup => m_Wrapper.m_Controls_UsePowerup;
        public InputActionMap Get() { return m_Wrapper.m_Controls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsActions set) { return set.Get(); }
        public void AddCallbacks(IControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Add(instance);
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @InteractA.started += instance.OnInteractA;
            @InteractA.performed += instance.OnInteractA;
            @InteractA.canceled += instance.OnInteractA;
            @CancelB.started += instance.OnCancelB;
            @CancelB.performed += instance.OnCancelB;
            @CancelB.canceled += instance.OnCancelB;
            @MenuStart.started += instance.OnMenuStart;
            @MenuStart.performed += instance.OnMenuStart;
            @MenuStart.canceled += instance.OnMenuStart;
            @PowerupScrollLeft.started += instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.performed += instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.canceled += instance.OnPowerupScrollLeft;
            @PowerupScrollRight.started += instance.OnPowerupScrollRight;
            @PowerupScrollRight.performed += instance.OnPowerupScrollRight;
            @PowerupScrollRight.canceled += instance.OnPowerupScrollRight;
            @UsePowerup.started += instance.OnUsePowerup;
            @UsePowerup.performed += instance.OnUsePowerup;
            @UsePowerup.canceled += instance.OnUsePowerup;
        }

        private void UnregisterCallbacks(IControlsActions instance)
        {
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @InteractA.started -= instance.OnInteractA;
            @InteractA.performed -= instance.OnInteractA;
            @InteractA.canceled -= instance.OnInteractA;
            @CancelB.started -= instance.OnCancelB;
            @CancelB.performed -= instance.OnCancelB;
            @CancelB.canceled -= instance.OnCancelB;
            @MenuStart.started -= instance.OnMenuStart;
            @MenuStart.performed -= instance.OnMenuStart;
            @MenuStart.canceled -= instance.OnMenuStart;
            @PowerupScrollLeft.started -= instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.performed -= instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.canceled -= instance.OnPowerupScrollLeft;
            @PowerupScrollRight.started -= instance.OnPowerupScrollRight;
            @PowerupScrollRight.performed -= instance.OnPowerupScrollRight;
            @PowerupScrollRight.canceled -= instance.OnPowerupScrollRight;
            @UsePowerup.started -= instance.OnUsePowerup;
            @UsePowerup.performed -= instance.OnUsePowerup;
            @UsePowerup.canceled -= instance.OnUsePowerup;
        }

        public void RemoveCallbacks(IControlsActions instance)
        {
            if (m_Wrapper.m_ControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlsActions @Controls => new ControlsActions(this);

    // ControlsV2
    private readonly InputActionMap m_ControlsV2;
    private List<IControlsV2Actions> m_ControlsV2ActionsCallbackInterfaces = new List<IControlsV2Actions>();
    private readonly InputAction m_ControlsV2_Camera;
    private readonly InputAction m_ControlsV2_Movement;
    private readonly InputAction m_ControlsV2_Sprint;
    private readonly InputAction m_ControlsV2_InteractA;
    private readonly InputAction m_ControlsV2_CancelB;
    private readonly InputAction m_ControlsV2_MenuStart;
    private readonly InputAction m_ControlsV2_PowerupScrollLeft;
    private readonly InputAction m_ControlsV2_PowerupScrollRight;
    private readonly InputAction m_ControlsV2_UsePowerup;
    private readonly InputAction m_ControlsV2_JumpSpace;
    public struct ControlsV2Actions
    {
        private @PlayerControls m_Wrapper;
        public ControlsV2Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Camera => m_Wrapper.m_ControlsV2_Camera;
        public InputAction @Movement => m_Wrapper.m_ControlsV2_Movement;
        public InputAction @Sprint => m_Wrapper.m_ControlsV2_Sprint;
        public InputAction @InteractA => m_Wrapper.m_ControlsV2_InteractA;
        public InputAction @CancelB => m_Wrapper.m_ControlsV2_CancelB;
        public InputAction @MenuStart => m_Wrapper.m_ControlsV2_MenuStart;
        public InputAction @PowerupScrollLeft => m_Wrapper.m_ControlsV2_PowerupScrollLeft;
        public InputAction @PowerupScrollRight => m_Wrapper.m_ControlsV2_PowerupScrollRight;
        public InputAction @UsePowerup => m_Wrapper.m_ControlsV2_UsePowerup;
        public InputAction @JumpSpace => m_Wrapper.m_ControlsV2_JumpSpace;
        public InputActionMap Get() { return m_Wrapper.m_ControlsV2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsV2Actions set) { return set.Get(); }
        public void AddCallbacks(IControlsV2Actions instance)
        {
            if (instance == null || m_Wrapper.m_ControlsV2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlsV2ActionsCallbackInterfaces.Add(instance);
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @InteractA.started += instance.OnInteractA;
            @InteractA.performed += instance.OnInteractA;
            @InteractA.canceled += instance.OnInteractA;
            @CancelB.started += instance.OnCancelB;
            @CancelB.performed += instance.OnCancelB;
            @CancelB.canceled += instance.OnCancelB;
            @MenuStart.started += instance.OnMenuStart;
            @MenuStart.performed += instance.OnMenuStart;
            @MenuStart.canceled += instance.OnMenuStart;
            @PowerupScrollLeft.started += instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.performed += instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.canceled += instance.OnPowerupScrollLeft;
            @PowerupScrollRight.started += instance.OnPowerupScrollRight;
            @PowerupScrollRight.performed += instance.OnPowerupScrollRight;
            @PowerupScrollRight.canceled += instance.OnPowerupScrollRight;
            @UsePowerup.started += instance.OnUsePowerup;
            @UsePowerup.performed += instance.OnUsePowerup;
            @UsePowerup.canceled += instance.OnUsePowerup;
            @JumpSpace.started += instance.OnJumpSpace;
            @JumpSpace.performed += instance.OnJumpSpace;
            @JumpSpace.canceled += instance.OnJumpSpace;
        }

        private void UnregisterCallbacks(IControlsV2Actions instance)
        {
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @InteractA.started -= instance.OnInteractA;
            @InteractA.performed -= instance.OnInteractA;
            @InteractA.canceled -= instance.OnInteractA;
            @CancelB.started -= instance.OnCancelB;
            @CancelB.performed -= instance.OnCancelB;
            @CancelB.canceled -= instance.OnCancelB;
            @MenuStart.started -= instance.OnMenuStart;
            @MenuStart.performed -= instance.OnMenuStart;
            @MenuStart.canceled -= instance.OnMenuStart;
            @PowerupScrollLeft.started -= instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.performed -= instance.OnPowerupScrollLeft;
            @PowerupScrollLeft.canceled -= instance.OnPowerupScrollLeft;
            @PowerupScrollRight.started -= instance.OnPowerupScrollRight;
            @PowerupScrollRight.performed -= instance.OnPowerupScrollRight;
            @PowerupScrollRight.canceled -= instance.OnPowerupScrollRight;
            @UsePowerup.started -= instance.OnUsePowerup;
            @UsePowerup.performed -= instance.OnUsePowerup;
            @UsePowerup.canceled -= instance.OnUsePowerup;
            @JumpSpace.started -= instance.OnJumpSpace;
            @JumpSpace.performed -= instance.OnJumpSpace;
            @JumpSpace.canceled -= instance.OnJumpSpace;
        }

        public void RemoveCallbacks(IControlsV2Actions instance)
        {
            if (m_Wrapper.m_ControlsV2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlsV2Actions instance)
        {
            foreach (var item in m_Wrapper.m_ControlsV2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlsV2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlsV2Actions @ControlsV2 => new ControlsV2Actions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_NavigateMenu;
    private readonly InputAction m_UI_SelectSubmit;
    private readonly InputAction m_UI_Back;
    private readonly InputAction m_UI_PauseUnpause;
    public struct UIActions
    {
        private @PlayerControls m_Wrapper;
        public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NavigateMenu => m_Wrapper.m_UI_NavigateMenu;
        public InputAction @SelectSubmit => m_Wrapper.m_UI_SelectSubmit;
        public InputAction @Back => m_Wrapper.m_UI_Back;
        public InputAction @PauseUnpause => m_Wrapper.m_UI_PauseUnpause;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @NavigateMenu.started += instance.OnNavigateMenu;
            @NavigateMenu.performed += instance.OnNavigateMenu;
            @NavigateMenu.canceled += instance.OnNavigateMenu;
            @SelectSubmit.started += instance.OnSelectSubmit;
            @SelectSubmit.performed += instance.OnSelectSubmit;
            @SelectSubmit.canceled += instance.OnSelectSubmit;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @PauseUnpause.started += instance.OnPauseUnpause;
            @PauseUnpause.performed += instance.OnPauseUnpause;
            @PauseUnpause.canceled += instance.OnPauseUnpause;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @NavigateMenu.started -= instance.OnNavigateMenu;
            @NavigateMenu.performed -= instance.OnNavigateMenu;
            @NavigateMenu.canceled -= instance.OnNavigateMenu;
            @SelectSubmit.started -= instance.OnSelectSubmit;
            @SelectSubmit.performed -= instance.OnSelectSubmit;
            @SelectSubmit.canceled -= instance.OnSelectSubmit;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @PauseUnpause.started -= instance.OnPauseUnpause;
            @PauseUnpause.performed -= instance.OnPauseUnpause;
            @PauseUnpause.canceled -= instance.OnPauseUnpause;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IControlsActions
    {
        void OnCamera(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteractA(InputAction.CallbackContext context);
        void OnCancelB(InputAction.CallbackContext context);
        void OnMenuStart(InputAction.CallbackContext context);
        void OnPowerupScrollLeft(InputAction.CallbackContext context);
        void OnPowerupScrollRight(InputAction.CallbackContext context);
        void OnUsePowerup(InputAction.CallbackContext context);
    }
    public interface IControlsV2Actions
    {
        void OnCamera(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteractA(InputAction.CallbackContext context);
        void OnCancelB(InputAction.CallbackContext context);
        void OnMenuStart(InputAction.CallbackContext context);
        void OnPowerupScrollLeft(InputAction.CallbackContext context);
        void OnPowerupScrollRight(InputAction.CallbackContext context);
        void OnUsePowerup(InputAction.CallbackContext context);
        void OnJumpSpace(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigateMenu(InputAction.CallbackContext context);
        void OnSelectSubmit(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnPauseUnpause(InputAction.CallbackContext context);
    }
}
